### ISSUE TITLE
Hotkeys in 12.3.1

### ISSUE THREAD

**Issue by namit252** [tlefko/Matebook-X-Pro-2018-Monterey#14]
Thanks for your EFI 
hotkey shortcuts like volume control, brightness don't work in monterey version 12.3.1

**Comment by tlefko** [comment]
> Thanks for your EFI
> hotkey shortcuts like volume control, brightness don't work in monterey version 12.3.1

Hmmm, very strange, check that your function keys are off as to control the brightness. (check sys prefs) you can test this using the Fn key and pressing brightness up. Also, within keyboard shortcuts you can manually assign the key you would like (as a workaround)
