### ISSUE TITLE
Installer goes into UEFI Interactive Shell

### ISSUE THREAD

**Issue by akmarwah03** [tlefko/Matebook-X-Pro-2018-Monterey#18]
Hey Everyone,
I am trying to install Monterey using the Opencore Method and the EFI files from macOS.Monterey.2.1.8.zip

1. Format USB FAT32
2. Add EFI Folder from repo and change serial/rom stuff using propertree
3. Download Monterey recovery files from commandline and paste into com.apple.recovery.boot folder in usb
4. Boot from USB
5. Select Tool

Installer should come

![062c5710-f905-48a6-a015-80e126837be6](https://user-images.githubusercontent.com/78773141/175365176-491aa412-dc65-4fb3-bfe3-4ee20a4d0a57.jpg)
![3738479a-24ee-4cdc-a3ad-f680b1ca6ceb](https://user-images.githubusercontent.com/78773141/175365138-93951717-34f1-4f96-8256-7587eb67262f.jpg)

**Comment by tlefko** [comment]
> Hey Everyone, I am trying to install Monterey using the Opencore Method and the EFI files from macOS.Monterey.2.1.8.zip
> 
> Steps to reproduce the behavior:
> 
> 1. Format USB FAT32
> 2. Add EFI Folder from repo and change serial/rom stuff using propertree
> 3. Download Monterey recovery files from commandline and paste into com.apple.recovery.boot folder in usb
> 4. Boot from USB
> 5. Select Tool
> 
> Installer should come
> 
> ![062c5710-f905-48a6-a015-80e126837be6](https://user-images.githubusercontent.com/78773141/175365176-491aa412-dc65-4fb3-bfe3-4ee20a4d0a57.jpg) ![3738479a-24ee-4cdc-a3ad-f680b1ca6ceb](https://user-images.githubusercontent.com/78773141/175365138-93951717-34f1-4f96-8256-7587eb67262f.jpg)

Hey! so there is a few issues with this method. For some reason there is issues letting OC detect the USB when doing it this way. use Createinstallmedia on a real mac as detailed on the instructions. if this issue persist, try rolling to an earlier release for installations

**Comment by akmarwah03** [comment]
Thanks a lot, my Mac is up nd running
<img width="1500" alt="Screen Shot 2022-06-24 at 1 23 54 AM" src="https://user-images.githubusercontent.com/78773141/175495773-54bfba34-462c-45fa-8216-0f246ebcaf5c.png">
