### ISSUE TITLE
Low Volume From Internal Speakers and Audio Jack

### ISSUE THREAD

**Issue by akmarwah03** [tlefko/Matebook-X-Pro-2018-Monterey#22]
Hey Everyone,
I have completed the mac os installation but the audio from the internal speakers seems to be really low with no bass and audio from headphones have instruments but no vocals. Bluetooth headphones seems to work fine with audio/

1. Go to youtube
2. Play any song on internal speakers or headphone

Expected behavior
Clear loud audio

Screenshots
![image](https://user-images.githubusercontent.com/78773141/180952791-a13f38ac-679d-4e71-a224-7dbaa6ab4812.png)

Errors I am seeing
OCS:No schema for MaximumGain at 5 index, context <audio>
OCS:No schema for MinimumAssistGain at 6 index, context <audio>
OCS:No schema for MinimumAudibleGain at 7 index, context <audio>

**Comment by tlefko** [comment]
leet me check this out @akmarwah03, can you try using a previous release? I'm curious if there is an issue with just the latest or all.

**Comment by akmarwah03** [comment]
Hey @tlefko, sorry about this, I installed windows and found out this was a hardware issue, my speakers in windows sound the same, I recently replaced my keyboard and maybe speakers got damaged.
