### ISSUE TITLE
Machine Hang on Bootup

### ISSUE THREAD

**Issue by myselfghost** [tlefko/Matebook-X-Pro-2018-Monterey#3]
During machine startup, the hang time is too long

**Comment by tlefko** [comment]
This is likely due to the bluetooth firmware driver failing to load. we can test this. after startup; see if bluetooth will actually enable. if it doesn’t. press sleep, wait a minute, and see if it works. if it does the issue is it failing to inject and we can work from there.

**Comment by myselfghost** [comment]
> This is likely due to the bluetooth firmware driver failing to load. we can test this. after startup; see if bluetooth will actually enable. if it doesn’t. press sleep, wait a minute, and see if it works. if it does the issue is it failing to inject and we can work from there.

looks like what you describe

**Comment by tlefko** [comment]
> > This is likely due to the bluetooth firmware driver failing to load. we can test this. after startup; see if bluetooth will actually enable. if it doesn’t. press sleep, wait a minute, and see if it works. if it does the issue is it failing to inject and we can work from there.
> 
> looks like what you describe

let me figure out exactly how to resolve this, a temporary fix is disabling bluetoolfixup and intel bluetooth in the config plist which would stop the hanging, but also d disable bluetooth. At present i’m not sure how to continually make sure it doesn’t hang as monterey change the way macos handles bluetooth since the rewrote the driver

**Comment by myselfghost** [comment]
> > > This is likely due to the bluetooth firmware driver failing to load. we can test this. after startup; see if bluetooth will actually enable. if it doesn’t. press sleep, wait a minute, and see if it works. if it does the issue is it failing to inject and we can work from there.
> > 
> > 
> > looks like what you describe
> 
> let me figure out exactly how to resolve this, a temporary fix is disabling bluetoolfixup and intel bluetooth in the config plist which would stop the hanging, but also d disable bluetooth. At present i’m not sure how to continually make sure it doesn’t hang as monterey change the way macos handles bluetooth since the rewrote the driver

thank you

**Comment by tlefko** [comment]
@myselfghost this should be fixed in latest release

**Comment by tlefko** [comment]
> > > > This is likely due to the bluetooth firmware driver failing to load. we can test this. after startup; see if bluetooth will actually enable. if it doesn’t. press sleep, wait a minute, and see if it works. if it does the issue is it failing to inject and we can work from there.
> > > 
> > > 
> > > looks like what you describe
> > 
> > 
> > let me figure out exactly how to resolve this, a temporary fix is disabling bluetoolfixup and intel bluetooth in the config plist which would stop the hanging, but also d disable bluetooth. At present i’m not sure how to continually make sure it doesn’t hang as monterey change the way macos handles bluetooth since the rewrote the driver
> 
> thank you

hey, check out the last release. should fix everything for ya
