### ISSUE TITLE
bluetooth not working after sleep

### ISSUE THREAD

**Issue by francescodesu** [tlefko/Matebook-X-Pro-2018-Monterey#4]
Thank you so much for releasing this.
The new version is working flawless and the battery is now lasting much longer.

I have just a problem: bluetooth not working even after putting the computer to sleep...
In the previous version it was working after sleep.

Any idea on how to fix it?
<img width="659" alt="Screen Shot 2022-03-24 at 0 42 40" src="https://user-images.githubusercontent.com/102243264/159738773-bc0e75ab-089e-4a78-880f-e8b919e00913.png">

**Comment by tlefko** [comment]
@francescodesu thank you very much! im glad it helped and that the battery life improved. within the config plist, you can enable intelbluetoothinjector.kext (kernel section) and intelbluetoothfirmware.kext. This is basically garaunteed to cause the boot hang again, but battery life and all that should still be okay. It is highly recommend you update to 12.3 if you are on 12.2.1 has a bluetooth battery drain bug. if not, stay on the current version you’re on!

**Comment by tlefko** [comment]
> Thank you so much for releasing this. The new version is working flawless and the battery is now lasting much longer.
> 
> I have just a problem: bluetooth not working even after putting the computer to sleep... In the previous version it was working after sleep.
> 
> Any idea on how to fix it? <img alt="Screen Shot 2022-03-24 at 0 42 40" width="659" src="https://user-images.githubusercontent.com/102243264/159738773-bc0e75ab-089e-4a78-880f-e8b919e00913.png">

Also, recommend to disable power nap, enable low power mode. it won't really effect performance, but greatly help battery some more.

**Comment by yonathanarya** [comment]
Thanks for the EFI provided in this repo. Just a quick feedback, to enable bluetooth, you only need to enable the IntelBluetoothFirmware.kext without the IntelBluetoothInjector.kext. Now I can use the bluetooth even without go to sleep first and no hang at boot.

**Comment by tlefko** [comment]
> Thanks for the EFI provided in this repo. Just a quick feedback, to enable bluetooth, you only need to enable the IntelBluetoothFirmware.kext without the IntelBluetoothInjector.kext. Now I can use the bluetooth even without go to sleep first and no hang at boot.

You’re brilliant, I can’t believe I left that oversight in there. They conflict. I’ll publish a new release with this as the default. Thank you
