### ISSUE TITLE
> Good Afternoon!. Thanks so much for your quick response.

### ISSUE THREAD

**Issue by tlefko** [tlefko/Matebook-X-Pro-2018-Monterey#7]
> Good Afternoon!. Thanks so much for your quick response.
> 
> > This is trying to boot the installed macos on your ssd correct?
> 
> Right.
> 
> > Please try using an earlier release (for now) and send me the result.
> 
> I changed to EFI 1.01 release. As usual, I download the zip file, unzip, and modify the SMBIOS info in the config.plist. Without any other change, I copied the whole OC folder to my EFI partition to replace the existing OC folder. The OC picker screen shows up correctly. When I select the first icon, there is no output, just black screen, so I have nothing to capture for your info. After several seconds, it goes back to OC picker screen again.
> 
> > this isn’t bapppening when trying to boot installer only the OS on the profzei drive?
> 
> Nope. I can boot to my macos with Profzei's EFI and it works well, except for the abnormal sleep. The bluetooth doesn't work after a deep sleep. And 5-language warning screen shows when pushing power button after hibernation.

okay. this is the error (i think, maybe lol). try this. don’t modify the config, i think the editor you’re using is corrupting it. try booting with vanilla installation and let me know. if it works i’ll edit the config for you. Sometimes using like OC configurator with version mismatches can cause this.

_Originally posted by @tlefko in https://github.com/tlefko/Matebook-X-Pro-2018-Monterey/issues/6#issuecomment-1094409055_

**Comment by elfzweik** [comment]
I tried copying the whole folder without modifying anything. But it is the same failure. In fact, I used ProperTree to modify the config.plist. It should be safe.

**Comment by tlefko** [comment]
hmmm… can you try booting the installer?

**Comment by elfzweik** [comment]
OK. It seems the only way left. I will try it. But as it costs time to reinstall the system and softwares, I need to seek time to do it. And will come back briefing you the result. Thanks for the help.

**Comment by elfzweik** [comment]
I tried booting the installer. Booting from a usb with your EFI. The installer goes into the installing procedure. But when the system restarted, the same thing happened. Either Macos installer or Macos shows the same screen as before. I have to change to profzei's EFI to finish the installation. 
BTW, my BIOS is v1.28. Could this be the cause?
